name: Release

env:
  SUBWASM_VERSION: 0.17.0

on:
  push:
    tags:
      - 'b*'

jobs:
#   srtool:
#     name: Build ${{ matrix.chain }}
#     strategy:
#       fail-fast: false
#       matrix:
#         chain: [ "bifrost-kusama", "bifrost-polkadot" ]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check to latest commit
#         uses: actions/checkout@v3




#       - name: Upload log
#         uses: actions/upload-artifact@v2
#         with:
#           name: log
#           path: log.txt


  release:
    name: Create Release
#     needs: srtool
    runs-on: ubuntu-latest
    steps:
      - name: Check to latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"



#      - name: Srtool build bifrost-kusama
#        id: srtool_build_kusama
#        uses: chevdor/srtool-actions@v0.5.0
#        env:
#          BUILD_OPTS: "--features on-chain-release-build"
#          PARACHAIN_PALLET_ID: "0x05"
#          AUTHORIZE_UPGRADE_PREFIX: "0x02"
#        with:
#          chain: bifrost-kusama
#          runtime_dir: runtime/bifrost-kusama
#
#      - name: Summary bifrost-kusama
#        run: |
#          mkdir -p ${{ github.workspace }}/artifacts
#          mv ${{ steps.srtool_build_kusama.outputs.wasm_compressed }} ${{ github.workspace }}/artifacts/
#
#      - name: Srtool build bifrost-polkadot
#        id: srtool_build_polkadot
#        uses: chevdor/srtool-actions@v0.5.0
#        env:
#          BUILD_OPTS: "--features on-chain-release-build"
#          PARACHAIN_PALLET_ID: "0x05"
#          AUTHORIZE_UPGRADE_PREFIX: "0x02"
#        with:
#          chain: bifrost-polkadot
#          runtime_dir: runtime/bifrost-polkadot
#
#      - name: Summary bifrost-polkadot
#        working-directory: ${{ github.workspace }}
#        run: |
#          mv ${{ steps.srtool_build_polkadot.outputs.wasm_compressed }} ${{ github.workspace }}/artifacts/
#
#      - name: Install toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly-2022-07-24
#          components: rustfmt
#          target: wasm32-unknown-unknown
#          default: true
#
#      - name: Build bifrost
#        working-directory: ${{ github.workspace }}
#        run: |
#          make build-all-release
#          mv ${{ github.workspace }}/target/release/bifrost ${{ github.workspace }}/artifacts/
#          pushd ${{ github.workspace }}/artifacts
#          sha256sum bifrost | tee bifrost.sha256
#          shasum -c bifrost.sha256
#          popd
#
#      # We now get extra information thanks to subwasm,
#      - name: Install subwasm ${{ env.SUBWASM_VERSION }}
#        run: |
#          wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
#          sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
#          subwasm --version
#
#      - name: Subwasm info
#        run: |
#          echo "# Upgrade Priority
#
#          Low: This is a low priority release and you may upgrade at your convenience." >> ${{ github.workspace }}-CHANGELOG.txt
#          echo "## Bifrost Kusama Runtime" >> ${{ github.workspace }}-CHANGELOG.txt
#          echo '```' >> ${{ github.workspace }}-CHANGELOG.txt
#          subwasm info ${{ github.workspace }}/artifacts/bifrost_kusama_runtime.compact.compressed.wasm >> ${{ github.workspace }}-CHANGELOG.txt
#          echo '```' >> ${{ github.workspace }}-CHANGELOG.txt
#          echo ' ' >> ${{ github.workspace }}-CHANGELOG.txt
#          echo "## Bifrost Polkadot Runtime" >> ${{ github.workspace }}-CHANGELOG.txt
#          echo '```' >> ${{ github.workspace }}-CHANGELOG.txt
#          subwasm info ${{ github.workspace }}/artifacts/bifrost_polkadot_runtime.compact.compressed.wasm >> ${{ github.workspace }}-CHANGELOG.txt
#          echo '```' >> ${{ github.workspace }}-CHANGELOG.txt

#       - name: Download build result for job apk
#         uses: actions/download-artifact@v2
#         with:
#           name: log

#       - name: Subwasm info
#         run: |
#           echo ${{ steps.changelog.outputs.changelog }} >> log2.txt
#
#       - name: Create Release
#         id: create_release
#         uses: softprops/action-gh-release@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           generate_release_notes: true
#           append_body: true
#           body_path: log2.txt
#           files: |
#             log2.txt
#             log.txt
#            ${{ github.workspace }}/artifacts/bifrost
#            ${{ github.workspace }}/artifacts/bifrost.sha256
#            ${{ github.workspace }}/artifacts/bifrost_kusama_runtime.compact.compressed.wasm
#            ${{ github.workspace }}/artifacts/bifrost_polkadot_runtime.compact.compressed.wasm

#       - uses: 8398a7/action-slack@v3
#         if: failure()
#         with:
#           status: ${{ job.status }}
#           fields: repo,author,eventName,workflow,ref,commit
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

#             ${{ github.workspace }}/artifacts/bifrost
#             ${{ github.workspace }}/artifacts/bifrost.sha256
